/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Runner;

import Boss.server;
import Client.client;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;

/**
 *
 * @author Siniša
 */
public class GUI extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GUIProgram
     */
    public GUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);


        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome to remote desktop");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 200, 30);

        jButton1.setText("Share your screen");
         getContentPane().add(jButton1);
        jButton1.setBounds(100, 80, 200, 50);
        jButton1.addActionListener(this);

        jButton2.setText("Look at friends screen");
         getContentPane().add(jButton2);
        jButton2.setBounds(100, 153, 200, 50);
        jButton2.addActionListener(this);
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    int countS = 0;
    int countC = 0;
    
    
    // End of variables declaration              
     @Override
     public void actionPerformed(ActionEvent e) {     
           if(e.getSource() == jButton1 && countC <1){            
                  countC++;
                  client c = new client ();
                  Thread t = new Thread(c);
                  t.start();
                  
           }
          
            if(e.getSource() == jButton2 && countS < 1 ){                
                try{
                  countS++;
                  server s = new server ();
                  Thread t = new Thread(s);
                  t.start();
                }
                catch (Exception a){}
            }
           
           
        }
        public void windowClosing(WindowEvent e) {     
        }

        public void windowOpened(WindowEvent e) {}
        public void windowActivated(WindowEvent e) {}
        public void windowIconified(WindowEvent e) {}
        public void windowDeiconified(WindowEvent e) {}
        public void windowDeactivated(WindowEvent e) {}
        public void windowClosed(WindowEvent e) {}
      
}
